source("/home/aivo/kool/R/mydistfun.R")
require(graphics)
# this is autogenerated test data
load(file="/home/aivo/kool/R/kNN_data1.RData")

library('lattice')
library("class")
library("scatterplot3d")
library("car")
library("rgl")

# create a rotation matrix, so we can obtain rotation vector using matrix multiplication
# https://en.wikipedia.org/wiki/Rotation_matrix

rotation <- matrix(,2,2); #2 row, 2 col
rotation[1,1] <- 0;
rotation[1,2] <- -1;
rotation[2,1] <- 1;
rotation[2,2] <- 0

# remove 3rd column from input
x1 <- x[, 1:2]
# rotate by matrix multiplication
x2 <- x1 %*% rotation

# calculate coordinate axes
x_axes <- seq(-10, 10, by=0.5)
y_axes <- x_axes

# calc cov matrixes for the distance fn
cov1 <- cov(x1)
cov2 <- cov(x2)

# create base matrices to use in dist calculations. first is 0, second 1-101 in 2 dimensions
m1 <- matrix(0:0, nrow = 2, ncol = 1)
m2 <- matrix(0:0, nrow = 2, ncol = 1)
# and one for cosine distance
m3 <- matrix(1:1, nrow = 2, ncol = 1)

# create surfaces
s1<-matrix(,101,101)
s2<-matrix(,101,101)
s3<-matrix(,101,101)
s4<-matrix(,101,101)
s5<-matrix(,101,101)
s6<-matrix(,101,101)
s7<-matrix(,101,101)
s8<-matrix(,101,101)
s9<-matrix(,101,101)

# fill the surfaces with data
for (i in 1:nrow(s1)){
  m2[1,1]=x_axes[i]
  for  (j in 1:nrow(s1)){
    m2[2,1]=y_axes[j]
    # Minkovski distance function at orders 1-5
    s1[i,j]=minkovski(m1,m2, 1) 
    s2[i,j]=minkovski(m1,m2, 2) 
    s3[i,j]=minkovski(m1,m2, 3) 
    s4[i,j]=minkovski(m1,m2, 4)
    s5[i,j]=minkovski(m1,m2, 5) 
    # Canberra distance
    s6[i,j]=canberra(m1,m2)
    # Mahalanobis distance
    s7[i,j]=mahabadist(m1,m2, cov1)
    s8[i,j]=mahabadist(m1,m2, cov2)
    # Cosine distance
    s9[i,j]=cosinedist(m3, m2)
  }
}

open3d()
persp3d(x_axes, y_axes, z1,alpha=0.5, col="green")
persp3d(x_axes, y_axes, z2,alpha=0.5, col="red",add=T)
persp3d(x_axes, y_axes, z3,alpha=0.5, col="blue",add=T)
persp3d(x_axes, y_axes, z4,alpha=0.5, col="grey",add=T)
persp3d(x_axes, y_axes, z5,alpha=0.5, col="brown",add=T)
persp3d(x_axes, y_axes, z6,alpha=0.5, col="yellow",add=T)
points3d(x1[,1], x1[,2], 0,alpha=0.5, col="green", add=T)
points3d(x2[,1], x2[,2], 0,alpha=0.5, col="blue", add=T)
persp3d(x_axes, y_axes, z7,alpha=0.5, col="grey",add=T)
persp3d(x_axes, y_axes, z8,alpha=0.5, col="pink",add=T)
persp3d(x_axes, y_axes, z9,alpha=0.5, col="orange",add=T)




